#!/usr/bin/env bash

# Usage:
# ./solc [options] inputfile > outfile

# Notes:
# - writing to files is not supported.
# - input files must be in the current directory

docker run -i --rm --user $(id -u):$(id -g) -v $(pwd):/tmp --workdir /tmp bd2d535eb5f3 $@
